### PR TITLE
Add scaffolding to enable snap build of commento

### PR DESCRIPTION
**Pull request by popey**
Thanks for making commento! It's a great compliment to other free software tools that I already use like Nikola for static site generation. I look forward to being able to migrate away from disqus! :)

This prototype PR adds the configuration and support files to generate a snap of commento. Snaps can be installed on multiple Linux distributions, are secure, and can be updated by the developer on their own cadence. Once landed, you can go to http://build.snapcraft.io/ and have it build and publish commento automatically to the edge channel in the store on every commit to master. Once published, users can install the latest build with ```snap install commento --edge```. When you're ready to release, you can can release to the stable channel, where users can easily install in the same way, omitting the ```--edge``` parameter. You can find out more about snaps at http://snapcraft.io/

To test this PR on an Ubuntu 16.04 machine:-

```
$ sudo apt install git snapcraft
$ git clone https://github.com/popey/commento
$ cd commento
$ git checkout add-snapcraft
$ snapcraft
$ sudo snap install *.snap --dangerous
```

(the ```--dangerous``` part is just because it's an unsigned package built locally rather than from the store).

I had to wrap commento in a little script so that it could find the web assets and put the sqlite3 db in the right location.

### CODE REVIEW

**Comment by adtac** [comment]
Hey @popey - thanks for the PR! I'm just finishing up for today (it's pretty late where I'm at), so I'll look into this tomorrow :)

**Comment by evandandrea** [comment]
Hi @adtac. Any luck with this? I can confirm locally that this builds, installs, and runs without issue. It'd be great to see commento available in the Snap Store.

**Comment by adtac** [comment]
@gitmate-bot rebase

**Comment by adtac** [comment]
@evandandrea hey there! I tried out snap on a Ubuntu 16.04 VPS and this is pretty neat. However, is there any way to install npm and build the frontend minified files? That is, currently, with this snap config, the server can only serve `commento.js` and `commento.css` files. However if you install npm and do a `npm install` followed by a `npm build`, two minified files will be generated. Commento will automatically serve these files.

I was just wondering if it's possible to build this into the snapcraft. You can see the Dockerfile for hints.

CC @popey

**Comment by adtac** [comment]
It's just that the project has changed a lot since the time this PR was made (with how the frontend is built and stuff).

**Comment by evandandrea** [comment]
Yes. This works for me:

```yaml
name: commento
version: git
summary: A lightweight, open source, tracking-free comment engine alternative to Disqus
description: |
  An open source, lightweight, and tracking-free comment engine.

grade: stable
confinement: strict

apps:
  commento: 
    command: launch_commento
    plugs:
      - network
      - network-bind

parts:
  scripts:
    plugin: dump
    source: snap/scripts
    organize:
      'launch': bin/
  assets:
    plugin: nodejs
    source: .
    npm-run:
      - build
    build:
      cp -r assets $SNAPCRAFT_PART_INSTALL
  commento:
    plugin: go
    source: .
    go-importpath: github.com/adtac/commento
    build-packages:
      - build-essential
```

**Comment by adtac** [comment]
Cherry-picked with a few modifications and rebases here: https://github.com/adtac/commento/pull/123

(Commit author information is intact.)

**Pull request closed without merging**
