### PR TITLE
Use flag pkg to control app options

### LINKED ISSUE #49: Use flags instead of environment variables for arguments
Flags may be easier to manage and control for instances. 

``` go
var (
                port = flag.Int("port", 8080, "http server port")
                demo = flag.Bool("demo", false, "use commento demo server")
)

func main(){

flag.Parse()

// .. and usage
 if *demo {
                fmt.Println("clearing")
// ..
svr := &http.Server{
                Addr:         fmt.Sprintf(":%d", *port),
                ReadTimeout:  5 * time.Second,
                WriteTimeout: 10 * time.Second,
}
```

### PR DESCRIPTION
**Pull request by lccezinha**
Fix #49 issue.

Using flag pkg to controle app options, instead read it from OS env vars.

### CODE REVIEW

**Comment by peteretelej** [comment]
@lccezinha please see [issues/49#issuecomment-298349596](https://github.com/adtac/commento/issues/49#issuecomment-298349596), @GaiusMartius had a good suggestion on using 12 factor app philosophy of [defining configs using env vars](https://12factor.net/config) and suggested use of dotenv to manage env vars if need. 

In this case,the `demo` env var would remain in place, while the port be passed as a flag, also part of PR #39, also pending; may be worth waiting on

**Comment by lccezinha** [comment]
@peteretelej Nice, I will read it soon.

**Comment by DarkThrone** [comment]
I agree with @peteretelej, Commento is more align with a web service than a system daemon. Also, with this approach we can have a set of sensible defaults that make the application more readable.

**Comment by adtac** [comment]
Since we went with environment variables, I don't think this can be merged anymore. Closing for now; feel free to reopen for discussion if you like.

**Comment by lccezinha** [comment]
Thanks @adtac !

**Pull request closed without merging**
