### PR TITLE
Remove binary from git

### PR DESCRIPTION
**Pull request by peteretelej**

### CODE REVIEW

**Comment by adtac** [comment]
ack https://github.com/adtac/commento/pull/81/commits/e616962e904e0596004b8db37bcc2b282968c73e

**Comment by adtac** [comment]
@peteretelej requires a rebase before merge (`git pull --rebase origin master`)

**Comment by peteretelej** [comment]
@adtac done.

**Comment by adtac** [comment]
ack https://github.com/adtac/commento/pull/81/commits/9cabb81680b160c8c4fdfd12972e54d9e013199c

**Pull request merged**
