### PR TITLE
Submit comment on enter when on name field (#74)

### LINKED ISSUE #74: Make Enter submit comment when on Name input field
It would be nice to have Enter (Return) submit the comment form when we are already on Name (comment author field). 

(Maybe even allow Ctrl + Enter in comment input field for submitting?)

### PR DESCRIPTION
**Pull request by rodorgas**
Hi,

This allows the user to submit the comment by pressing enter when on name field. Closes #74

### CODE REVIEW

**Comment by adtac** [comment]
ack https://github.com/adtac/commento/pull/99/commits/7fb89993f837447b4ab52b316962bb74f6be5dad

**Comment by adtac** [comment]
Ugh, it looks like gitmate is stuck for some reason.

@rodorgas Can you please empty amend this commit (just a `git commit --amend` would do) and force push (`git push --force`)?

**Comment by rodorgas** [comment]
Done! Is it OK now?

**Comment by sils** [comment]
ack 336bdd4

**Comment by sils** [comment]
ack 336bdd4

**Comment by sils** [comment]
@adtac there's no webhooks arriving at GitMate, did you turn it off?

**Comment by adtac** [comment]
ack https://github.com/adtac/commento/commit/336bdd47ee7f700c989eed924bf4c1b0fedb63a0

**Comment by adtac** [comment]
ack https://github.com/adtac/commento/commit/336bdd47ee7f700c989eed924bf4c1b0fedb63a0

**Comment by adtac** [comment]
@rodorgas I had already cherry-picked your commit yesterday: https://github.com/adtac/commento/pull/101

I had to do this because a couple of other PRs were pending as well. You're still the commit author, of course :)

**Pull request closed without merging**
