### PR TITLE
Golang community will be moving to the dep tool

### PR DESCRIPTION
**Pull request by GaiusMartius**
Using a vendor directory for the js assets will mean clashing with the new dependency management standard for the golang community.
With the dep tool installed (See: https://github.com/golang/dep) the developer needs only to execute the following commands to create a binary:
`
dep ensure
`
`
go build
`

### CODE REVIEW

**Comment by caarlos0** [comment]
golang/dep does not work on heroku yet, though...

**Comment by GaiusMartius** [comment]
Hey Becker, I mention dep because it is where the golang community will be heading though I'm currently using glide myself. Since golang 1.6 there has been consensus on the use of a vendor directory to store dependencies so I wanted to suggest the project move in that direction.
Using a vendor directory for the js assets will certainly be painful going forward since almost all the dependency tools for golang will wipe it out and overwrite it. Making the assumption that a golang dependency tool will not overwrite would tie this project to that tool specifically.

As for use with heroku, I would vendor the dependencies ahead of time before pushing the code. I'm not aware of what all the PaaS's would need to make this project work so I'm targeting the common denominator which is vendoring dependencies into the source folder.

**Comment by caarlos0** [comment]
@GaiusMartius yeah, I know, I use dep in a lot of projects, just pointed out that if the idea is to publish to heroku, last time I checked, it didn't work (adding the vendor folder should fix it though).

**Comment by adtac** [comment]
Hey @GaiusMartius 

Thanks for the PR. I didn't know about `vendor` becoming a reserved directory. Anyway, a PR prior to yours moved all the JS/CSS files to a `assets` directory and we're going with that (instead of `src`).

Also, since I'm merging other PRs at the same time (my mistake, I shouldn't have put this off for so long), we'll have a bunch of merge conflicts. So if it's okay with you, I'll cherry-pick your commit and make a mega PR (you'll still be the author of your PR). I'll amend your commit to make the `src` to `assets` change too.

**Comment by adtac** [comment]
Cherry-picked and merged here: https://github.com/adtac/commento/pull/35

Of course, he commit author information is unchanged.

Thanks!

**Pull request closed without merging**
