### PR TITLE
README changes about the use of the Golang dep tool

### PR DESCRIPTION
**Pull request by GaiusMartius**

### CODE REVIEW

**Comment by DarkThrone** [comment]
`dep` is still in *Alpha* from the README.me

>Alpha. Functionality is known to be broken, missing or incomplete. Command and file format changes are still planned. The repository is open to solicit feedback and contributions from the community. Please see below for feedback and contribution guidelines.

Are we sure we want a tool that could be broken any time?

**Comment by peteretelej** [comment]
I don't think we should use dep yet, until it stabilizes, otherwise the state of commento would be tied to a project in alpha.

**Comment by GaiusMartius** [comment]
> Are we sure we want a tool that could be broken any time?

There is more functionality to be built out but commento is, fortunately, relying on only the most basic use case.
That is, the developer is only asked to enter
`dep ensure`
To get all of their dependencies.

The alternative would be either to
1) Not use a vendoring tool and check in all the dependencies into the github repo. That will make the repo far more heavy than it would otherwise be plus, updating the dependencies will mean git commits that have many lines of diffs that are separate from the code we're changing
2) Use a different vendoring tool. For that case we will end up back at dep eventually since most developers will move to it. That means we will be changing away from dep now and that means we'll need to do updates to our code then back to it in the future which will need more updates.

I'd be willing to switch away if there were an alternative vendoring tool that is an agreed upon standard and our use case is more complex. For us, however, the tool is being used just to fetch dependencies.
The largest change I see is how the Gopkg.* files are used but those are small changes if they happen. The dep tool will be standard within a year or so and that will be helpful for devs coming in because they'll already know what to do.

**Comment by DarkThrone** [comment]
commento relies in the only use case the tool supports which is vendoring third party libraries. It's clearly stated in the project that the commands and the description file are going to change, and documentation suggest that the tool would be in a usable state after Go 1.9, and even though it could be that `dep` won't be merged with the rest of the toolchain at all.

I rather look into other more stablished solutions, like gopm or godep, until `dep` stabilises.

About 1, if that is a solid medium term solution, I'd prefer that.

The same could be said in 2 for `dep` chances are it not merged or modified. I'd put my money on a deps vendoring tool that is proven to work and then migrating to `dep` would it be available and stable.

In an oss project I think is better to have a clear upgrading path, than gambling with the time of contributors for the sake of using the latest and most cutting-edge.

**Comment by adtac** [comment]
So as I mentioned in the other PR, dep is now relatively stable (ever since go1.9 released). It's definitely the direction the community is moving in, so let's go with it. Besides, as @GaiusMartius said, we're not using much of the functionality of dep apart from `dep ensure`.

@GaiusMartius I have added in your changes through a different PR: too much had changed since this PR, so I thought that'd be easier.

**Pull request closed without merging**
