### PR TITLE
Add MySQL as a database backend

### PR DESCRIPTION
**Pull request by zorchenhimer**
This addresses #167, although gob isn't used.  To compile without SQLite support: `go build -tags no_sqlite`.  Same thing for MySQL but with the `no_mysql` tag instead.  Both are included by default.

### CODE REVIEW

**Comment by adtac** [comment]
@zorchenhimer thanks a lot for the PR! Apologies for the late reply, I've been meaning to review this for two weeks, but I've been really busy. I'll review this over this weekend :+1:

**Comment by adtac** [comment]
and +1 for using nice commit messages :)

**Comment by zorchenhimer** [comment]
>and +1 for using nice commit messages :)

My coworkers have the shortest, most useless, commit messages and it drives me up a wall, lol.

**Comment by adtac** [comment]
@zorchenhimer didn't mean to close this, sorry. I renamed the master branch (into `v0`) and github auto-closed all PRs without a notification. I'll cherry-pick this commit in a separate PR (you'll still be the commit author) as I can't re-open this PR. Apologies :/

**Comment by zorchenhimer** [comment]
No worries.  I may just make another pull request because I committed my changes to the master branch in my fork instead of its own branch, and that's been bugging me for a while, lol.

**Comment by jozsefsallai** [comment]
Any updates on this, @adtac? I'd love to use Commento on my blog but I don't want to install yet another database system (besides, I'm not a big fan of postgres).

**Comment by adtac** [comment]
@jozsefsallai PostgreSQL is pretty baked into Commento at this point. When this PR was made, Commento was on v0 and v0 has been unmaintained and unsupported for over a year now. The patch is probably still valid for the v0 branch (the `v0` branch still available in this repo), but it is not applicable to the current version (see the master branch). And Commento, for reasons good or bad, uses a lot of Postgres-isms hard coded.

I evaluated the pros and cons of supporting multiple backends a year ago using ORMs, but I discarded the option on grounds of poor performance. I don't regret my decision either; having to deal with just one database backend has made a lot of things simpler and better. Given how baked in Postgres is, I don't foresee Commento supporting MySQL for a long time. I'm sorry.

Just out of curiosity, why do you dislike Postgres?

**Pull request closed without merging**
