### PR TITLE
Add delete endpoint for comments

### PR DESCRIPTION
**Pull request by nkprince007**

### CODE REVIEW

**Comment by adtac** [comment]
Umm, this would allow anybody to delete anybody else's comments, right? That's definitely not what we want.

We want a dashboard-like thing where ONLY the admin has the power to delete comments. Therefore, this must not be an exposed endpoint. Especially without authentication.

Am I missing something?

**Comment by nkprince007** [comment]
Yeah, uhm, we need authentication, but no endpoint has one right now.

**Comment by adtac** [comment]
Yeah, we can't add delete functionality unless we can identify that the person deleting the comment is:
 - the author
 - the site admin

For the first one, we would have to store some sort of identification on the client side. That amounts to a level of tracking and I'll have to think about that.

The site admin thing is more feasible - with a password-protected moderation dashboard, the site admin can choose to delete comments at will. I will be implementing the dashboard in a while, so this will certainly be one of the most important features there.

For now, this PR is blocked/won't merge.

**Comment by chuyskywalker** [comment]
It might be reasonable to accept this as-is with the single addition of making it only accept requests from localhost (`127.0.0.1`) so that you could issue these rest calls directly as an owner of the server, but not from anywhere.

**Comment by adtac** [comment]
@chuyskywalker that might work, but I'm still uncomfortable merging this. The proper way to do this would be to use an authentication token and we would be able to do that when there's a moderation dashboard (which will happen soon).

**Comment by adtac** [comment]
One more problem with accepting requests from localhost: if you run Commento behind nginx, for example, *all* requests will be from localhost. If we're whitelisting IPs, we should also make sure `X-Forwarded-For` is empty. There are other additional checks as well, probably.

**Pull request closed without merging**
